POST http://localhost:5000/app/registermember
Content-Type: application/json

{
    "firstName":"Lil",
    "lastName":"Pump",
    "username":"gucciman",
    "password":"boost",
    "age":23,
    "donations":100
}