POST http://at715casestudy.herokuapp.com/app/registermember
Content-Type: application/json

# {
#     "fullName":"Testing date 1",
#     "title": "testing date 1",
#     "message": "Hello welcome to the website. It is important you are here"
# }

{
    "firstName":"FullstackTest1",
    "lastName":"FullstackTest1",
    "username":"FullstackTest1",
    "password":"man",
    "age":44,
    "donations":1000
}

